version: "3.7"
services:
  smartparking-db:
    container_name: smartparking-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    ports:
      - "27017:27017"
    networks: 
      - smartparking-network
    
  smartparking-api:
    container_name: smartparking-api
    build:
      context: Backend\ReactiveSmartparking-api\target\docker
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - smartparking-db
    links:
     - smartparking-db
    networks: 
      - smartparking-network
      
  smartparking-monitor:
    container_name: smartparking-monitor
    build:
      context: Frontend\angular
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - smartparking-api
    links:
      - smartparking-api
    networks: 
      - smartparking-network
      
networks: 
  smartparking-network:
    driver: bridge
