version: "3"
services:
  smartparking-db:
    container_name: smartparking-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodb
      MONGO_INITDB_ROOT_PASSWORD: mongodb
    ports:
    - "27017:27017"
    networks:
    - smartparking-network

  smartparking-api:
    container_name: smartparking-api
    image: smartparking-api:latest
    environment:
    - SPRING_DATA_MONGODB_HOST=smartparking-db
    ports:
    - "8081:8081"
    depends_on:
    - smartparking-db
    links:
    - smartparking-db
    networks:
      - smartparking-network

networks:
  smartparking-network:
    driver: bridge

