logging:
  level:
    web: DEBUG
    org:
      springframework:
        data: DEBUG

spring:
  application:
    name: ReactiveSmartParking

  profiles:
    active: dev

  devtools:
    restart:
        enabled: true
    livereload:
        enabled: true
    add-properties: false

  data:
    mongodb:
      #   uri: mongodb+srv://admin:admin@smartparking-bzlwo.azure.mongodb.net/smartparking?retryWrites=true&w=majority
      host: localhost
      port: 27017
      password: mongodb
      username: mongodb
      authentication-database: admin

server:
  port: 8081
