logging:
  level:
    web: DEBUG
    org:
      springframework:
        data: DEBUG

spring:
  application:
    name: ReactiveSmartParking

  profiles:
      active: dev

  devtools:
    restart:
        enabled: true
    livereload:
        enabled: true
    add-properties: false

  data:
    mongodb:
      uri: mongodb+srv://admin:admin@smartparking-bzlwo.azure.mongodb.net/smartparking?retryWrites=true&w=majority

server:
    port: 8081

# TODO docker run -p 8081:8081 -it smartparking-api:1.0.0-SNAPSHOT --network="host

